/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DBConnection.DatabaseConnector;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Simon
 */
public class Administration extends javax.swing.JFrame {

    private final DatabaseConnector dbConnector = new DatabaseConnector();
    /**
     * Creates new form Administration
     */
    public Administration() {
        SetupUIComponents();
        LoadSessionDetails();
    }
    
    private void SetupUIComponents(){
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private void LoadSessionDetails(){
        tblSessionDetails.removeAll();
        DefaultTableModel model = (DefaultTableModel) tblSessionDetails.getModel();
        
        ArrayList<String[]> sessionDetails = dbConnector.GetSessionDetails();
        for (String[] sessionDetailsRow : sessionDetails) {
            model.addRow(sessionDetailsRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSessionDetails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administraion");
        setResizable(false);

        panContainer.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblSessionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Number", "Is Blocked?", "Geo Location", "IP Address", "Device Name", "MAC Address", "Time In", "Risk Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSessionDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSessionDetails);
        if (tblSessionDetails.getColumnModel().getColumnCount() > 0) {
            tblSessionDetails.getColumnModel().getColumn(0).setResizable(false);
            tblSessionDetails.getColumnModel().getColumn(3).setResizable(false);
            tblSessionDetails.getColumnModel().getColumn(4).setResizable(false);
            tblSessionDetails.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout panContainerLayout = new javax.swing.GroupLayout(panContainer);
        panContainer.setLayout(panContainerLayout);
        panContainerLayout.setHorizontalGroup(
            panContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContainerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panContainerLayout.setVerticalGroup(
            panContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panContainer;
    private javax.swing.JTable tblSessionDetails;
    // End of variables declaration//GEN-END:variables
}
